[project]
name = "demo-text-to-sql"
version = "0.1.0"
description = "Demo Text-to-SQL"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.4",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.32.0",
    "multinear>=0.1.0",
    "sqlalchemy>=2.0.36",
    "faker>=33.1.0",
]
